"""Emit results/macros.tex with every number the paper cites, from real results.

Run after the experiments finish. The paper \\input's this file, so prose never
hard-codes a measured value. Missing results fall back to \\providecommand
placeholders so the paper still compiles mid-experiment.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CODE = ROOT / "code"
OUT = ROOT / "paper" / "macros.tex"


def pct(x) -> str:
    return f"{round(100 * x)}\\%" if x is not None else "--"


def load(p: Path) -> dict:
    return json.loads(p.read_text()) if p.exists() else {}


def main() -> None:
    lines = ["% Auto-generated by scripts/make_macros.py — do not edit by hand.",
             "% Re-run after experiments to refresh every measured value.\n"]

    def cmd(name: str, val: str) -> None:
        lines.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    main_s = load(CODE / "results/main/qwen3.5-9b/summary.json")
    for cond, tag in [("zeroshot", "ZS"), ("single_agent", "SA"), ("quantigence", "QU")]:
        s = main_s.get(cond, {})
        cmd(f"acc{tag}", pct(s.get("accuracy")))
        cmd(f"lat{tag}", f"{s.get('avg_latency_s', 0):.0f}" if s else "--")
        cv = s.get("citation_validity")
        cmd(f"citeval{tag}", pct(cv) if cv is not None else "--")
    qu = main_s.get("quantigence", {})
    cmd("toolQU", f"{qu.get('avg_tool_calls', 0):.1f}" if qu else "--")
    vram = qu.get("peak_vram_mb")
    cmd("vramMB", str(vram) if vram else "--")
    cmd("vramGB", f"{vram/1024:.1f}" if vram else "--")

    # complex-task evaluation
    cx = load(CODE / "results/complex/summary.json")
    for cond, tag in [("zeroshot", "ZS"), ("single_agent", "SA"), ("quantigence", "QU")]:
        s = cx.get(cond, {})
        cmd(f"cov{tag}", pct(s.get("mean_coverage")) if s else "--")
        cmd(f"qual{tag}", f"{s.get('mean_quality', 0):.2f}" if s else "--")

    # scale study
    for tag, key in [("FourB", "qwen3.5-4b"), ("NineB", "qwen3.5-9b"),
                     ("FourteenB", "qwen3-14b")]:
        s = load(CODE / f"results/scale/{key}/summary.json").get("quantigence", {})
        if not s and key == "qwen3.5-9b":
            s = qu  # reuse main run for the 9B point
        cmd(f"acc{tag}", pct(s.get("accuracy")))
        v = s.get("peak_vram_mb")
        cmd(f"vram{tag}", f"{v/1024:.1f}" if v else "--")

    # robustness: retrieval (deterministic) + generation (judged)
    rob = load(CODE / "results/robustness/summary.json")
    retr = rob.get("retrieval", {})
    gen = rob.get("generation", {})
    cmd("poisonTopkNone", f"{retr.get('none', {}).get('mean_poison_in_topk', 0):.2f}"
        if retr else "--")
    cmd("poisonTopkHier", f"{retr.get('source_hierarchy', {}).get('mean_poison_in_topk', 0):.2f}"
        if retr else "--")
    cmd("poisonRankOneNone", pct(retr.get("none", {}).get("poison_at_rank1_rate"))
        if retr else "--")
    cmd("poisonK", str(retr.get("none", {}).get("k", 5)) if retr else "5")
    for tag, key in [("None", "none"), ("All", "all")]:
        r = gen.get(key, {})
        cmd(f"asr{tag}", pct(r.get("attack_asr")))
        cmd(f"util{tag}", pct(r.get("utility")))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines)-3} macros)")


if __name__ == "__main__":
    main()
